name: ci
on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint

  typecheck:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Get the repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run type-check
        run: npm run type-check

  build:
    runs-on: ubuntu-latest
    needs: typecheck
    steps:
      - name: Get the repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build